/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bcia_javachain_csp_gm_sdt_jni_SMJniApi */

#ifndef _Included_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
#define _Included_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_PARAM
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_PARAM 4097L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_MAKEKEY
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_MAKEKEY 4098L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM2SIGN
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM2SIGN 4099L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM2VERIFY
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM2VERIFY 4100L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM2ENC
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM2ENC 4101L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM2DEC
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM2DEC 4102L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM4ECBENC
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM4ECBENC 4103L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM4ECBDEC
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM4ECBDEC 4104L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM4CBCENC
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM4CBCENC 4105L
#undef org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM4CBCDEC
#define org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_SMJNIAPI_ERR_SM4CBCDEC 4106L
/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nRandomGen
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nRandomGen
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM2MakeKey
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM2MakeKey
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM2KDF
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM2KDF
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM2Sign
 * Signature: ([BI[BI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM2Sign
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM2Verify
 * Signature: ([BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM2Verify
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM2Encrypt
 * Signature: ([BI[BI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM2Encrypt
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM2Decrypt
 * Signature: ([BI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM2Decrypt
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM3Hash
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM3Hash
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM4ECBEncrypt
 * Signature: ([BI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM4ECBEncrypt
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM4ECBDecrypt
 * Signature: ([BI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM4ECBDecrypt
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM4CBCEncrypt
 * Signature: ([BI[BI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM4CBCEncrypt
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     org_bcia_javachain_csp_gm_sdt_jni_SMJniApi
 * Method:    nSM4CBCDecrypt
 * Signature: ([BI[BI[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_bcia_javachain_csp_gm_sdt_jni_SMJniApi_nSM4CBCDecrypt
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
